### GENERAL SETTINGS ###

# Site settings
title: Lauren Ancona
description: "Data visualization, map design & web analytics."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://laurenancona.github.io"
keep_files: [./maps, ./parking, ./resources, ./examples]

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#9299A5" #"#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary:  "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url: https://dribbble.com/laurenancona  
  - title: twitter
    url: https://twitter.com/laurenancona  
  - title: instagram
    url: https://instagram.com/laurenancona  
  - title: github
    url: https://github.com/laurenancona  
  - title: linkedin
    url: https://linkedin.com/in/laurenancona  
  - title: medium
    url: https://medium.com/@laurenancona  

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
email: ancona.lauren@gmail.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Lauren Ancona
    position: Data Visualization and Map design
    text: 
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ancona.lauren#gmail.com
      - title: twitter
        url: http://twitter.com/laurenancona

    
# Clients information. Shown on Home and About pages.
press:
  - name: CNN.com
    img: cnn.png
  - name: CityLab
    img: citylab.png
  - name: Independent.co.uk
    img: independent.png
  - name: PhillyMag
    img: phillymag.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A classically-trained musician turned data scientist in the City of Brotherly Love."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO